

gwc : $(OBJS) meschach.a
	$(CC) $(OBJS) $(EFENCE) $(LFLAGS) $(LIBS) -o gwc

audio_device.o : audio_device.c audio_alsa.c audio_oss.c audio_osx.c
	$(COMPILE) -c audio_device.c

.c.o :
	$(COMPILE) -c $<
